BUSH: str = "sprites/bush.png"
PLAYER_1: str = "sprites/player_1.png"
PLAYER_2: str = "sprites/player_2.png"
GRASS_A: str = "sprites/grass_pattern_A.png"
GRASS_B: str = "sprites/grass_pattern_B.png"
GRASS_C: str = "sprites/grass_pattern_C.png"
GRASS_D: str = "sprites/grass_pattern_D.png"
EGG_POSITIVE: str = "sprites/egg_positive.png"
EGG_NEGATIVE: str = "sprites/egg_negative.png"
GOLDEN_EGG: str = "sprites/golden_egg.png"
GAME_ICON: str = "sprites/game_icon.jpg"
GRID_SIZE: int = 35
GRID_X: int = 20
GRID_Y: int = 20
GAME_TICK: int = 10
MATCH_TIME: int = 180
MAX_POINTS: int = 30
FONT: str = "Pixeloid sans"
FONT_SIZE: int = 20
BLACK: tuple[int, int, int] = (0, 0, 0)
WHITE: tuple[int, int, int] = (255, 255, 255)
TRANSPARENT: tuple[int, int, int, int] = (0, 0, 0, 0)
