BUSH: str = "assets/Sprites/bush.png"
PLAYER_1: str = "assets/Sprites/player_1.png"
PLAYER_2: str = "assets/Sprites/player_2.png"
GRASS_A: str = "assets/Sprites/grass_pattern_A.png"
GRASS_B: str = "assets/Sprites/grass_pattern_B.png"
GRASS_C: str = "assets/Sprites/grass_pattern_C.png"
GRASS_D: str = "assets/Sprites/grass_pattern_D.png"
EGG_POSITIVE: str = "assets/Sprites/egg_positive.png"
EGG_NEGATIVE: str = "assets/Sprites/egg_negative.png"
GOLDEN_EGG: str = "assets/Sprites/golden_egg.png"
GAME_ICON: str = "assets/Icon/game_icon.png"
GAME_MUSIC: str = "assets/Sounds/game_music.wav"
EGG_COLLECT: str = "assets/Sounds/egg_collect.mp3"
GRID_SIZE: int = 35
GRID_X: int = 20
GRID_Y: int = 20
GAME_TICK: int = 10
MATCH_TIME: int = 180
MAX_POINTS: int = 30
FONT: str = "Pixeloid sans"
FONT_SIZE: int = 20
BLACK: tuple[int, int, int] = (0, 0, 0)
WHITE: tuple[int, int, int] = (255, 255, 255)
TRANSPARENT: tuple[int, int, int, int] = (0, 0, 0, 0)
